DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "customers";
DROP TABLE IF EXISTS "merchants";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "consultancies";
DROP TABLE IF EXISTS "sessions";
