// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Consultancy struct {
	ID         int64 `json:"id"`
	MerchantID int64 `json:"merchant_id"`
	CustomerID int64 `json:"customer_id"`
	// must be positive
	Cost      int64     `json:"cost"`
	CreatedAt time.Time `json:"created_at"`
}

type Customer struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	ImageUrl  string    `json:"image_url"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID         int64 `json:"id"`
	CustomerID int64 `json:"customer_id"`
	// might be positive or negative
	Amount    int64     `json:"amount"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Merchant struct {
	ID         int64     `json:"id"`
	Owner      string    `json:"owner"`
	Balance    int64     `json:"balance"`
	Profession string    `json:"profession"`
	Title      string    `json:"title"`
	About      string    `json:"about"`
	ImageUrl   string    `json:"image_url"`
	Rating     int32     `json:"rating"`
	CreatedAt  time.Time `json:"created_at"`
}

type Payment struct {
	ID         int64 `json:"id"`
	MerchantID int64 `json:"merchant_id"`
	CustomerID int64 `json:"customer_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PhoneNumber       string    `json:"phone_number"`
	ImageUrl          string    `json:"image_url"`
	Gender            string    `json:"gender"`
	Disabled          bool      `json:"disabled"`
	BirthDate         time.Time `json:"birth_date"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
