// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMerchantBalance(ctx context.Context, arg AddMerchantBalanceParams) (Merchant, error)
	CreateConsultancy(ctx context.Context, arg CreateConsultancyParams) (Consultancy, error)
	CreateCustomer(ctx context.Context, owner string) (Customer, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCustomer(ctx context.Context, id int64) error
	DeleteMerchant(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetConsultancy(ctx context.Context, id int64) (Consultancy, error)
	GetCustomer(ctx context.Context, id int64) (Customer, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetMerchant(ctx context.Context, id int64) (Merchant, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListConsultancies(ctx context.Context, arg ListConsultanciesParams) ([]Consultancy, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (User, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
